title: Dispersión Elástica 12C - Alpha
description: Dispersión elástica del carbono 12 con la partícula alfa utilizando un potencial complejo de Wood Saxon, modelo óptico.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
